### ISSUE TITLE
Add Vimeo icon

### ISSUE THREAD

**Issue by michaelhagedon** [az-digital/az-icons#17]
## Motivation
We're using az-icons via Quickstart 2 and we have a Vimeo account we want to link to.

### Is your feature request related to a problem? Please describe.
Vimeo is sad:
![image](https://user-images.githubusercontent.com/645924/155037230-0c0e4003-1e48-498f-b7bc-989fec96620f.png)

### Describe the solution you'd like
Make a Vimeo icon available in this repository. There's a Vimeo icon [in this footer](https://libguides.library.arizona.edu/library-guides) we could use maybe.

### Describe alternatives you've considered
- Not have an icon for Vimeo :-(

**Comment by trackleft** [comment]
Adding to 2.3.0 release, but can probably merge sooner

**Comment by michaelhagedon** [comment]
Even without a release, this is effectively deployed now if CloudFront caching doesn't interfere... I think?
