### ISSUE TITLE
Add shellcheck step to PR process.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az-icons#28]
## Motivation
Would be good to find errors in our bash files before updating the main branch.

I heard about this github action in a friday meeting https://github.com/marketplace/actions/shell-linter

**Comment by mmunro-ltrr** [comment]
And this isn't just for az-icons: anything that has uses a shell script would benefit from Shellcheck. I'd thought about writing up some coding standards to go with it, but hadn't done that. The biggest issue with standards were the cases where we'd cut & pasted code from elsewhere that was known to work well, but wouldn't have conformed.

**Comment by trackleft** [comment]
I'll add this to the other repos, thanks, I added a PR here: https://github.com/az-digital/az-icons/pull/29
