### ISSUE TITLE
Add dependabot config to .github folder.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az-icons#36]
## Conditions of satisfaction
- [ ] Same configuration as https://github.com/az-digital/arizona-bootstrap/blob/main/.github/dependabot.yml

**Comment by RyanDool** [comment]
> ## Conditions of satisfaction
> * [ ]  Same configuration as https://github.com/az-digital/arizona-bootstrap/blob/main/.github/dependabot.yml

@trackleft Reading up on dependabot and I am unsure if az-icons needs all of the elements that arizona-bootstrap has. I'm considering something along the lines of:


```version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    reviewers:
      - "az-digital/developers"
    open-pull-requests-limit: 10
    labels:
      - "ci"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "az-digital/developers"
    labels:
      - "ci"
